kind = "web"
previewPath = "/"
title = "Squadz"
version = "1.0.0"
id = "artifacts/squadz"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24614

[services.development]
run = "pnpm --filter @workspace/squadz run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/squadz", "run", "build" ]
publicDir = "artifacts/squadz/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24614"
BASE_PATH = "/"
