// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vault-redesign/CoverStory.tsx": () => import("../components/mockups/vault-redesign/CoverStory.tsx"),
  "./components/mockups/vault-redesign/InlineGallery.tsx": () => import("../components/mockups/vault-redesign/InlineGallery.tsx"),
  "./components/mockups/vault-redesign/MemoriesFeed.tsx": () => import("../components/mockups/vault-redesign/MemoriesFeed.tsx"),
  "./components/mockups/vault-redesign/MemoriesTimeline.tsx": () => import("../components/mockups/vault-redesign/MemoriesTimeline.tsx"),
  "./components/mockups/vault-redesign/SquadGallery.tsx": () => import("../components/mockups/vault-redesign/SquadGallery.tsx"),
  "./components/mockups/vault-redesign/ThumbnailStrip.tsx": () => import("../components/mockups/vault-redesign/ThumbnailStrip.tsx"),
  "./components/mockups/icon-picker/CategoryChips.tsx": () => import("../components/mockups/icon-picker/CategoryChips.tsx"),
  "./components/mockups/icon-picker/CuratedRow.tsx": () => import("../components/mockups/icon-picker/CuratedRow.tsx"),
  "./components/mockups/icon-picker/SearchableSheet.tsx": () => import("../components/mockups/icon-picker/SearchableSheet.tsx"),
  "./components/mockups/squad-channel/Current.tsx": () => import("../components/mockups/squad-channel/Current.tsx"),
  "./components/mockups/squad-channel/Quieter.tsx": () => import("../components/mockups/squad-channel/Quieter.tsx")
};
