// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/squad-channel/Current.tsx": () => import("../components/mockups/squad-channel/Current.tsx"),
  "./components/mockups/squad-channel/Quieter.tsx": () => import("../components/mockups/squad-channel/Quieter.tsx"),
  "./components/mockups/icon-picker/CategoryChips.tsx": () => import("../components/mockups/icon-picker/CategoryChips.tsx"),
  "./components/mockups/icon-picker/CuratedRow.tsx": () => import("../components/mockups/icon-picker/CuratedRow.tsx"),
  "./components/mockups/icon-picker/SearchableSheet.tsx": () => import("../components/mockups/icon-picker/SearchableSheet.tsx")
};
